import 'package:wine_shop_v2/models/wine.dart';

final List<Wine> wineList = [
  Wine(
    id: 1,
    picturePath: '/images/wine1.png',
    status: 'Unavailable',
    title: 'Philippe Fontaine Champagne Brut Rosé',
    type: 'Sparkling wine',
    origin: 'Champagne Blanc',
    isFavourite: true,
    score: 94,
    price: 23256596,
    size: 750, 
  ),
  Wine(
    id: 2,
    picturePath: '/images/wine2.png',
    status: 'Available',
    title: 'Chateau Margaux 2015',
    type: 'Red wine',
    origin: 'Bordeaux',
    isFavourite: false,
    score: 98,
    price: 53200000,
    size: 750,
  ),
  Wine(
    id: 3,
    picturePath: '/images/wine3.png',
    status: 'Available',
    title: 'Dom Pérignon Vintage 2008',
    type: 'Champagne',
    origin: 'France',
    isFavourite: false,
    score: 96,
    price: 2123456,
    size: 750,
  ),
  Wine(
    id: 4,
    picturePath: '/images/wine4.png',
    status: 'Available',
    title: 'Chateau Lafite Rothschild 2018',
    type: 'Red wine',
    origin: 'Pauillac',
    isFavourite: false,
    score: 97,
    price: 1234567,
    size: 750,
  ),
  Wine(
    id: 5,
    picturePath: '/images/wine1.png',
    status: 'Available',
    title: 'Chateau Mouton Rothschild 2018',
    type: 'Red wine',
    origin: 'Pauillac',
    isFavourite: false,
    score: 97,
    price: 1234567,
    size: 750,
  ),
  Wine(
    id: 6,
    picturePath: '/images/wine2.png',
    status: 'Available',
    title: 'Mileștii Mici Cabernet Sauvignon',
    type: 'Red wine',
    origin: 'Mileștii Mici',
    isFavourite: false,
    score: 95,
    price: 1234567,
    size: 750,
  ),
  Wine(
    id: 7,
    picturePath: '/images/wine3.png',
    status: 'Available',
    title: 'Cricova Fetească Albă',
    type: 'White wine',
    origin: 'Cricova',
    isFavourite: false,
    score: 94,
    price: 1234567,
    size: 750,
  ),
  Wine(
    id: 8,
    picturePath: '/images/wine4.png',
    status: 'Available',
    title: 'Purcari Rosu de Purcari',
    type: 'Red wine',
    origin: 'Purcari',
    isFavourite: false,
    score: 96,
    price: 1234567,
    size: 750,
  ),
  Wine(
    id: 9,
    picturePath: '/images/wine1.png',
    status: 'Available',
    title: 'Chateau Vartely Individo',
    type: 'Red wine',
    origin: 'Orhei',
    isFavourite: false,
    score: 95,
    price: 1234567,
    size: 750,
  ),
];
